options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _GITHUB_REPOSITORY: "sekou2109/purchase_predict_api.git" 

steps:
  - name: "ghcr.io/astral-sh/uv:python3.12-trixie-slim"
    id: CI
    entrypoint: /bin/sh
    args:
      - "-c"
      - "cd purchase-predict && chmod a+x install.sh && ./install.sh && uv sync && uv run pytest ."
    env:
      - "UV_CACHE_DIR=/root/.cache/uv"

  - name: "ghcr.io/astral-sh/uv:python3.12-trixie-slim"
    id: CD
    entrypoint: /bin/bash
    args:
      - "-c"
      - "cd purchase-predict && chmod a+x install.sh && ./install.sh && uv run kedro run"
    env:
      - "ENV=$BRANCH_NAME"
      - "MLFLOW_SERVER=$_MLFLOW_SERVER"
      - "DO_NOT_TRACK=1"
      - "UV_CACHE_DIR=/root/.cache/uv" 
    waitFor: ["CI"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: API Deploy
    secretEnv: ["GITHUB_FGT_API"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git clone --branch $BRANCH_NAME https://$$GITHUB_FGT_API@github.com/$_GITHUB_REPOSITORY /tmp/purchase_predict_api
        cd /tmp/purchase_predict_api
        gcloud builds submit \
          --config /tmp/purchase_predict_api/cloudbuild.yaml /tmp/purchase_predict_api \
          --substitutions=SHORT_SHA=$SHORT_SHA
    waitFor: ["CD"]

timeout: 1200s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/gcp-token-api/versions/latest
      env: GITHUB_FGT_API