steps:
  - name: "ghcr.io/astral-sh/uv:python3.12-trixie-slim"
    id: CI
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        cd purchase-predict
        chmod a+x install.sh
        ./install.sh
        uv sync
        uv run pytest .
    env:
      - "UV_CACHE_DIR=/root/.cache/uv"

options:
  logging: CLOUD_LOGGING_ONLY