# Liste des Cloud Builders : https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL
steps:
  - name: "ghcr.io/astral-sh/uv:python3.12-trixie-slim"
    id: CI
    entrypoint: /bin/sh
    args:
      - "-c"
      - "chmod a+x install.sh && ./install.sh && uv sync && uv run pytest ."
    env:
      - "UV_CACHE_DIR=/root/.cache/uv"

logs_bucket: gs://purchase_predict/logs_build_cloud_build